modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU Affero General Public License v3.0"
[[mods]] #mandatory
modId="momentumprotection" #mandatory
version="1.16.5-0.0.1" #mandatory
displayName="Momentum Protection" #mandatory
logoFile="momentumprotectionlogo.png" #optional
credits="" #optional
authors="Shutdoor" #optional
description='Adds a four level enchantment to Elytras to prevent a percentage of momentum damage.'
[[dependencies.momentumprotection]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.momentumprotection]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"